image: "python:3.9"

before_script:
  - python --version
  - pip install -r requirements.txt

stages:
  - test

job 1:
  stage: test
  script:
    - cd tests
    - pytest test.py -v
    - cd ../
    - cd src
    - pyinstaller --onefile main.py functions.py converter.py
    - cd ../
  artifacts:
    paths:
      - ./dist/main.exe