image: "python:3.7"

stages:
  - test

job 1:
  stage: test
  script:
    - CHCP 65001
    - pwd
    - ls -l
    - export PYTHONPATH="$PYTHONPATH:."
    - python -c "import sys;print(sys.path)"
    - pytest .\tests\test.py -v