image: python:3.9

stages:
  - test

before_script:
  # Установка окружения
  - echo "Install environment"
  - apt-get update -q -y
  - pip3 install -r requirements.txt

job 1:
  stage: test
  script:
    - CHCP 65001
    - pytest .\tests\test.py -v
