image: "python:3.9"

before_script:
  - pip install -r requirements.txt

stages:
  - python --version
  - test

job 1:
  stage: test
  script:
    - pwd
    - ls -l
    - export PYTHONPATH="$PYTHONPATH:."
    - python -c "import sys;print(sys.path)"
    - pytest .\tests\test.py -v