image: "python:3.9"

before_script:
  - python --version
  - pip install -r requirements.txt

stages:
  - test

job 1:
  stage: test
  script:
    - pytest ./tests/test.py -v
    - pyinstaller --onefile ./src/main.py ./src/functions.py ./src/converter.py
    - ls
    - cd dist
    - ls
    - cd main
    - ls
  artifacts:
    paths:
      - dist/main.exe